version: "3.8"

services:
  backend:
    build: ./backend
    image: gestao-escolar
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app.db:/app/app.db
    command: python -m uvicorn app:app --host 0.0.0.0 --port 8000
